### ISSUE TITLE
Fix performance on parking history and possibly search list page.

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#100]
The performance on the parking history page may not be optimal due the way mobx is used, this problem could due to implementation reasons also be present in the search list.

**Task breakdown**
- [ ] Look through the data handling in the two components.
- [ ] Fix any problems that are found.

**Success criteria**
- [ ] There should be no delay between the parking session ending and it showing up on the history page.
