### ISSUE TITLE
Fix distance on parking spots

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#101]
The distance on the parking spots is currently not set except for when they are searched for in the search list. They should always contain the distance to the user.

**Task breakdown**
- [ ] Calculate the distance to the user for parking spots and set this data point in the objects.
- [ ] Add new data point that can be set to the distance from the search result to the parking spot so that the search list sorting still works as intended.
- [ ] Make sure the search list uses this new data point.

**Success criteria**
- [ ] All locations where parking spot distance is shown should show the distance to the user.
