### ISSUE TITLE
Remove list active parking session button.

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#104]
Remove the button for the active parking session page.

**Task breakdown**
- [ ] Remove the bottom navigation button to the parking session page.
- [ ] Change the title to the parking session history page to "parking sessions"
- [ ] Show active parking sessions (as well) on the old parking session history page.
- [ ] Create new element for active parking sessions.

**Success Criteria**
Tasks should be completed.
