### ISSUE TITLE
Give the user feedback when a parkingsession is ended.

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#106]
As a user, I want there to be clear feedback to when I finish a parking session. 

**Task breakdown**
- [ ] When the user clicks on the finish button, give a visual response and then close the rent page (take the user back to the map)
- [x] Add text to show the user that the parkingspot is rented (on the rent parking spot page)
- [x] Change "Finish" to "End parking" on the rent button.
