### ISSUE TITLE
Make User name and icon visible again

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#121]
The user's name and icon is currently barely visible. Make sure it is visible again.

**Tasks**
- [ ] Change the color of the user name text to white.
- [ ] Make the user account icon visible by changing the background color or icon color.

**Acceptance Criteria**
- [ ] The icon and name of the user are visible.
