### ISSUE TITLE
Show a map

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#16]
As a user I want the application to be able to show my location on a map so I can see my location in relation to at least one parking spots.

**Task breakdown:**
- [x] Have map that covers the entire screen. 

- [x] See my current location on the map. 

- [x] See at least one parking spot on the map. 

- [x] Button to center the map on my current location. 

_The tasks are the acceptance criteria_ 

**Definition of Done**
Definition of done can be found in the social contract.
