### ISSUE TITLE
Search for parking spots

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#20]
As a user I want to be able search for parkings spots so that I can find spots that are nearby to where I want to park.

**Task breakdown:**
- [ ] ~~There is a text bar in the application.~~
- [ ] ~~When I type text in the text bar I search for parking spots.~~
- [x] The data for the list should be gathered from at least one data source.

_The tasks are the acceptance criteria_ 

**Definition of Done**
Definition of done can be found in the social contract.
