### ISSUE TITLE
Create selected map marker

### ISSUE THREAD

**Issue by neoncove** [dat256-weedle/weedle#39]
As a user i want to easily see the most important information (address, price, distance) to quickly gain info on the map. 

**Task Breakdown**
- [ ] Add a new map marker.
- [ ] The map marker should have:
    - [ ] Address text of the parking spot.
    - [ ] Distance text of the parking spot.
    - [ ] Price text of the parking spot.
    - [ ] A button to book the parking spot.
    - [ ] Logo of the provider of the parking spot.
- [ ] The book button should open the book parking spot page.
- [ ] Add event for when the user clicks anywhere else on the map that closes the map marker.
- [ ] Add a onClick on the search list elements that selects the parking spot and closes the list.

**Acceptance Criteria**
- [ ] Have a map marker that is bigger than the normal map marker.
- [ ] The bigger map marker should have the following information:
    - [ ] Address
    - [ ] Distance
    - [ ] Price
    - [ ] Book button.
    - [ ] Parking provider logo
- [ ] The book button should take the user to the booking page for the parkignspots.
- [ ] The marker should be closed whenever the user clicks anywhere else on the map.
- [ ] The bigger map marker should be opened whenever a normal map marker is clicked.
- [ ] The bigger map marker should be closed whenever another map marker is selected.
- [ ] The bigger map marker should also be opened whenever the list element for the parkingspot is clicked in the search list.
