### ISSUE TITLE
Rent parking spot page

### ISSUE THREAD

**Issue by neoncove** [dat256-weedle/weedle#40]
As a user I want to be able to rent a specific parking spot so that I can park my car.

**Task Breakdown**
- [x] Fullscreen page.
- [x] Link to this page from the map icons.
- [x] Show address, price and distance of the parkingspot.
- [x] Let the user choose car to park with.
- [x] One of (developer decides
    - [ ] Have two scrolls, one for hours and one for minutes to represent total time (and show end-date).  
    - [x] Have three scrolls to let the user determine an enddate (one scroll for each, day, hour, minute)
- [x] Have the rent button on it.

__Success critera is the same as the tasks__
