### ISSUE TITLE
Create User Page

### ISSUE THREAD

**Issue by neoncove** [dat256-weedle/weedle#41]
As a user of the application I want a page to see and change information about myself (email, my cars) to make the experience more convenient.

**Task Breakdown**
- [ ] See name 
- [ ] See email
- [ ] See cars (Registration numbers)
- [ ] Change mail (allow only valid mail addresses)
- [ ] Add cars
- [ ] Remove cars
- [ ] Have maximum of 4 cars.
- [ ] Save data locally

_The tasks are the acceptance criteria_ 

**Definition of Done**
Definition of done can be found in the social contract.
