### ISSUE TITLE
See accurate data

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#42]
As a developer I want to have real parking spot data.

**Task breakdown:**
- [ ] Gather data from a source.  

- [ ] Gather data from multiple sources.

- [ ] Convert data to a custom Json format. 

- [ ] Save data in store 

_The tasks are the acceptance criteria_ 

**Definition of Done**
Definition of done can be found in the social contract.
