### ISSUE TITLE
Have a menu

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#44]
As a user I want there to be a bottom menu so that I can reach the different pages of the application. 

**Task break**
- [x] Have a menu bar.
- [x] Add a button the menu bar.
- [x] Add multiple buttons to the menu.
- [x] There should be 4 buttons, one for the map, one for the profile page, one for active parkingspots (does not exist yet), one for history (does not exist) 
- [x] Make the buttons change pages.
_At the end of the sprint_: 
- [x] Integrate the existing pages with this navbar.

_The tasks are the acceptance criteria_ 

**Definition of Done**
Definition of done can be found in the social contract.
