### ISSUE TITLE
Common styling 

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#56]
As a user I want there to be some form of uniform styling in the application. This to make the application more appealing to me.

**Tasks**
- [ ] Create a stylesheet that follows the acceptance criteria.
- [ ] Go through all components in the application and make sure that they follow the stylesheet whereever necessary.

**Acceptance Criteria**
- [x] All components should have uniform font.
- [ ] When the same level of importance of information is present, they should have the same font-weight.
- [x] The primary color of the application is #BE55FF, the secondary color is #7427A9. These are the only colors a part from black and white as well as red for "danger" and blue for links that should be used in the application.
