### ISSUE TITLE
Long term storage of user preferences

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#57]
As a user I want the application to remember my preferences between sessions. This to not have to add all my preferences each time I start the application.

**Tasks**
- [ ] Find a solution to local long-term storage (between sessions).
- [ ] Use said solution to save Email.
- [ ] Use said solution to save cars.
- [ ] Load the saved data on application start.

**Acceptance Criteria**
- [ ] Following properties should be stored between sessions:
    - [ ] Email
    - [ ] Cars
