### ISSUE TITLE
List active parking sessions.

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#59]
As a car owner I want to be able to see my current parking sessions so that I can control the times for the active sessions.

**Task breakdown**
- [ ] Show a list of currently active parking sessions
- [ ] Show which car is concerned
- [ ] Show where it is parked (name of parkingspots)
- [ ] Show time remaining of the parking session.
