### ISSUE TITLE
History of parking sessions.

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#60]
As a car owner I want to be able to see history of parking sessions so that I can know which parking sessions I've paid for and also see how much money I've spent on parking.

**Tasks**
- [x] Create a fullscreen list.
- [x] Make the list scrollable.
- [x] Add a list element with the following properties: 
    - [x] Date
    - [x] Location
    - [ ] Paid or not
    - [x] Logo of parking provider.
- [x] If necessary add a button in the bottom navigation.
- [x] Link to this page from one of the buttons in the bottom navigation.
- [x] Gather the parking session data from the store.

**Acceptance Critera**
- [x] Should have a list.
- [x] List should be scrollable.
- [x] Show date of the parking session.
- [x] Show the location of the parking session.
- [x] Show if the parking session is paid or not.
- [x] Show a logo of the parking provider.
