### ISSUE TITLE
About us page

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#63]
As a customer I want to contact the provider of the application to supply me with a contact us / information page so that I know what the terms of service is for the application and know how I can contact the company. As a product owner I would like to provide users with a way of giving us feedback about the app. 

**Tasks**
- [x] Create a fullscreen page.
- [x] Add a dummy email address text.
- [x] Add dummy phone number text.
- [x] Add github issues page link.
- [x] Add a button to the user page.
- [x] Make the button open the about us page.

**Acceptance Criteria**
- [x] Have a Page with the following information.
    - [x] A dummy email address.
    - [x] A dummy phone number.
    - [x] A link to the github issues page.
- [x] On the user page, blow "my cars" add a button to open the About us page.
