### ISSUE TITLE
Add payment information

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#64]
As a user / company shareholder I want there to be a way for me to enter payment information on the user page.

**Tasks**
- [x] Add text field to user page for card number (allow exactly 16 numbers, add spaces/dashes between every 4).
- [x] Add text field for expiration date (number input, only allow valid months/years that hasn't been yet).
- [x] Add text field for ccc code (number input, accept 3 numbers).

**Acceptance criteria**
--- To user page --- 
- [x] There should be a text field for adding card number.
- [x] There should be a text field for adding card expiration date.
- [x] There should be a text field for adding card security code.
- [x] The input data should be validated.
