### ISSUE TITLE
Fix android compatability issues.

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#66]
Currently the map does not work properly on android platforms.

**Tasks (all apply for android specifically)** 
- [ ] Find my location button.
- [ ] Show my location.
- [ ] Show parking spot icons.
