### ISSUE TITLE
Make the list of parkingspots searchable.

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#68]
As a parking spot searcher I want there to be a list of nearbyspots so that I can search for them.

**Task Breakdown**
- [ ] Create a searchbar.
- [ ] Create a list view.
- [ ] Add the searchbar to the map view.
- [ ] Add the searchbar to the list view.
- [ ] Add address-search integration to get useful search results.
- [ ] Add list element with name, provider logo, distance to search result and price.
- [ ] Fill the list with relevant search results.
- [ ] Sort the search-list on distance to the search result.

**Acceptance Criteria**
- [x] There should be a searchbar on the map screen.
- [x] There should be a fullscreen list with the same searchbar at the top.
- [x] When the user types letters into the searchbar a the list screen shall replace the map.
- [x] The list should  be filled with Parkingspots related to the search.
- [x] The list should be sorted on distance.
- [x] The list should be scrollable.
- [x] Each list element should show at least:
    - [x] The provider of the parkingspot.
    - [x] The cost of the parkingspot.
    - [x] The name of the parkingspot.
    - [x] The distance from the search-location of the parkingspot.
