### ISSUE TITLE
Show the search list search results on the map

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#84]
As a parking spot searcher I want to be able to see the search results of my searches on the map.

**Tasks**
- [ ] When the search list elements are clicked save the parkingspots in the search.
- [ ] When the search list elements are clicked that opens the map.
- [ ] If there are search results only show the search result parking spots on the map.

**Acceptance criteria**
- [ ] When the user presses the enter key on the keyboard, close the list.
- [ ] When the list is closed only show the search results on the map and no other parking spots.
