### ISSUE TITLE
Increase performance by grouping map markers

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#85]
As a user of the application I want the application to be responsible when I do actions. 
As a user I want the map markers for the parking spots to be grouped when too many of them are in near vicinity.

**Tasks**
- [ ] Enable grouping for when parking spot markers are overlapping.
- [ ] Update the grouping when the zoom level of the map changes. 
- [ ] When the grouped markers are clicked the map should zoom to the area of the group.

**Acceptance criteria**
- [ ] Map markers should be group when they are overlapping.
- [ ] The groupings should be updated when the user zooms in and out on the map.
- [ ] When the grouped map markers are clicked the map should zoom to that area.
