### ISSUE TITLE
Fix styling where it is still incorrect

### ISSUE THREAD

**Issue by ViddeM** [dat256-weedle/weedle#96]
Currently, there is still inconsistent styling due to parallel work.

**Task breakdown**
- [x] Fix styling on parking session history header.
- [x] Fix styling on the user account page.
- [x] Make sure that the images on the account page are consistent in position.
- [ ] Make sure that the rent button shows when the user can click it.
- [x] The cars should be consistent.
- [x] Replace all green images/background color with the purple color defined in the style sheet.

**Success Criteria**
- [ ] The styling should be consistent for the abovementioned components.
